package net.engineeringdigest.journalApp.repository;

import net.engineeringdigest.journalApp.entity.User;
import org.bson.types.ObjectId;
import org.springframework.data.mongodb.repository.MongoRepository;

public interface UserRepository extends MongoRepository<User,ObjectId> {
    User findByUsername(String username);
}

//controller-->service --> repo
// -findByUsername
// methodname_fieldname





/*
Normally, Java cannot do this:
UserRepository repo = new UserRepository(); // ❌ Impossible
because interfaces cannot be instantiated.

But Spring creates a hidden class behind the scenes.
Something like:
class UserRepositoryImpl implements UserRepository {
    @Override
    public User findByUsername(String username) {
        // Generated by Spring
    }
    // Other MongoRepository methods...
}
You never see this class—it is generated automatically.
* */